### ISSUE TITLE
Errant Space in your python code

### ISSUE THREAD

**Issue by cpieper78** [aws-ia/cfn-ps-duo-mfa#11]
File: templates/duo-proxy-fargate.template.yaml
In line 1672 it appears there is an extra space that casuses the code to fail when running..
![CleanShot 2023-12-04 at 14 30 17@2x](https://github.com/aws-ia/cfn-ps-duo-mfa/assets/98427213/bafbe351-8607-488f-983e-78ba09f113f6)

**Comment by dennislaf** [comment]
Yup, getting this error now as well which seems to be related: `[ERROR] Runtime.UserCodeSyntaxError: Syntax error in module 'index': unexpected indent (index.py, line 9)
Traceback (most recent call last):
  File "/var/task/index.py" Line 9
     artifact_bucket = os.environ['DuoBucket']`

**Comment by vsnyc** [comment]
@cpieper78 Thank you for submitting the fix in PR https://github.com/aws-ia/cfn-ps-duo-mfa/pull/12
