### ISSUE TITLE
Invalid configuration error

### ISSUE THREAD

**Issue by davmayd** [aws-ia/cfn-ps-duo-mfa#16]
With the latest image updates, users are experiencing the following error in the ECS logs:

(UTC-6:00)	Your configuration is not valid. Check the validation output for errors.
(UTC-6:00)	Failed to start duoauthproxy: exit status 1
(UTC-6:00)	If the duoauthproxy failed to start for connectivity reasons, the connectivity tool located at /opt/duoauthproxy/bin/authproxy_connectivity_tool can be run independently to test for connectivity problems.
(UTC-6:00)	Unhandled Error
(UTC-6:00)	Traceback (most recent call last):
(UTC-6:00)	File "/opt/duoauthproxy/usr/local/lib/python3.8/site-packages/twisted/application/app.py", line 674, in run

**Comment by krzysiek-4** [comment]
`scripts/source/docker/Dockerfile` is updated.
But the Dockerfile inside `scripts/packages/code_commit.zip` is yet to be updated.

**Comment by davmayd** [comment]
@krzysiek-4 the most recent update is from last week (https://github.com/aws-ia/cfn-ps-duo-mfa/commit/4ab2271ef3b8bcd945c0afdf6d4ad820354fc8d1), and it's been uploaded to S3.

**Comment by davmayd** [comment]
According to the impacted customer, there are no longer any errors (confirmed with my account) but the function is no longer updating directory services to use the proxy

**Comment by davmayd** [comment]
Also, thank you @krzysiek-4 , updating the ZIP file did fix the issue (in the sense that the "configuration is not valid" error is no longer logged).

**Comment by krzysiek-4** [comment]
> According to the impacted customer, there are no longer any errors (confirmed with my account) but the function is no longer updating directory services to use the proxy

I notice this issue as well, this might cause the configuration not working as expected when the ECS Task being updated (IP change).

**Comment by davmayd** [comment]
This issue is resolved. The follow-up issue is being tracked at https://github.com/aws-ia/cfn-ps-duo-mfa/issues/18
