### ISSUE TITLE
Lambda function issues

### ISSUE THREAD

**Issue by pdimic** [aws-ia/cfn-ps-duo-mfa#18]
Hello, 
The Template deployed without issues after last weeks issues you addressed
Deployment into an existing VPC is done however the lambda functions dont show logs in cloudwatch and the function to update the settings on the direcotry service is not working. Shows as if it ran but no logs or changes are made to the environment.

Thanks
Peter

**Comment by davmayd** [comment]
The Lambda "RotateRadiusSharedSecret" shows the following error in the logs
![image](https://github.com/aws-ia/cfn-ps-duo-mfa/assets/51335587/2fd61ea1-97dd-41a1-bc71-8daea0493d5e)

**Comment by pdimic** [comment]
RotateRadiusSharedSecretFunction error as well

[ERROR] Runtime.UserCodeSyntaxError: Syntax error in module 'index': unexpected indent (index.py, line 11) Traceback (most recent call last):   File "/var/task/index.py" Line 11
--

**Comment by davmayd** [comment]
Fixed by https://github.com/aws-ia/cfn-ps-duo-mfa/pull/19
